name: ci_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
    - mlflow==2.19.0
    # Dependensi dari modelling.py:
    - pandas
    - scikit-learn
    - numpy  # Sering menjadi dependensi implisit dari pandas/sklearn
